# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 02:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asiento', models.PositiveSmallIntegerField()),
                ('estado_asiento', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_bus', models.CharField(max_length=45)),
                ('placa_bus', models.CharField(max_length=7)),
                ('capacidad_bus', models.PositiveSmallIntegerField()),
                ('asiento', models.ManyToManyField(to='SistemaBuses.Asiento')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('genero', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('hora_reserva', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad_partidad', models.CharField(max_length=45)),
                ('ciudad_llegada', models.CharField(max_length=45)),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('costo_destino', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaBuses.Bus')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaBuses.Ruta'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='reserva',
            field=models.ManyToManyField(to='SistemaBuses.Reserva'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
